# Generated by Django 5.2.4 on 2025-08-03 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_sid', models.CharField(blank=True, help_text='Account SID de Twilio', max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, help_text='Auth Token de Twilio', max_length=255, null=True)),
                ('twilio_phone_number', models.CharField(blank=True, help_text='Número de WhatsApp Business de Twilio (formato: +1234567890)', max_length=50, null=True)),
                ('whatsapp_business_token', models.TextField(blank=True, help_text='Token de acceso de WhatsApp Business API', null=True)),
                ('whatsapp_business_phone_id', models.CharField(blank=True, help_text='ID del número de teléfono de WhatsApp Business', max_length=255, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Activar/desactivar notificaciones')),
                ('notificar_remesas', models.BooleanField(default=True, help_text='Enviar notificaciones para nuevas remesas')),
                ('notificar_pagos', models.BooleanField(default=True, help_text='Enviar notificaciones para nuevos pagos')),
                ('notificar_cambios_estado', models.BooleanField(default=True, help_text='Enviar notificaciones para cambios de estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificación',
            },
        ),
        migrations.CreateModel(
            name='DestinatarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del destinatario', max_length=255)),
                ('telefono', models.CharField(help_text='Número de WhatsApp (formato: +1234567890)', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('recibir_remesas', models.BooleanField(default=True, help_text='Recibir notificaciones de remesas')),
                ('recibir_pagos', models.BooleanField(default=True, help_text='Recibir notificaciones de pagos')),
                ('recibir_cambios_estado', models.BooleanField(default=True, help_text='Recibir notificaciones de cambios de estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destinatario de Notificación',
                'verbose_name_plural': 'Destinatarios de Notificación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('remesa_nueva', 'Nueva Remesa'), ('remesa_estado', 'Cambio Estado Remesa'), ('pago_nuevo', 'Nuevo Pago'), ('pago_estado', 'Cambio Estado Pago')], max_length=20)),
                ('mensaje', models.TextField(help_text='Contenido del mensaje enviado')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('respuesta_api', models.TextField(blank=True, help_text='Respuesta de la API de WhatsApp', null=True)),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si falló el envío', null=True)),
                ('remesa_id', models.CharField(blank=True, help_text='ID de la remesa relacionada', max_length=50, null=True)),
                ('pago_id', models.IntegerField(blank=True, help_text='ID del pago relacionado', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.destinatarionotificacion')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
