# Generated by Django 5.2.4 on 2025-08-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='callmebot_api_key',
            field=models.CharField(blank=True, help_text='API Key de CallMeBot (obtenida enviando mensaje a +34 644 84 44 84)', max_length=255, null=True),
        ),
    ]
