# Generated by Django 5.2.4 on 2025-08-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_configuracionnotificacion_callmebot_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='callmebot_api_key',
            field=models.CharField(blank=True, help_text='API Key personal de CallMeBot para este número específico', max_length=255, null=True),
        ),
    ]
