# Generated by Django 5.2.4 on 2025-09-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_destinatarionotificacion_callmebot_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lognotificacion',
            name='tipo',
            field=models.CharField(choices=[('remesa_nueva', 'Nueva Remesa'), ('remesa_estado', 'Cambio Estado Remesa'), ('remesa_eliminada', 'Remesa Eliminada'), ('pago_nuevo', 'Nuevo Pago'), ('pago_estado', 'Cambio Estado Pago'), ('pago_eliminado', 'Pago Eliminado')], max_length=20),
        ),
    ]
