# Generated by Django 5.2.4 on 2025-09-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_alter_lognotificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='notificar_ediciones',
            field=models.BooleanField(default=True, help_text='Enviar notificaciones cuando se editen remesas o pagos'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_ediciones',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones de ediciones'),
        ),
        migrations.AlterField(
            model_name='lognotificacion',
            name='tipo',
            field=models.CharField(choices=[('remesa_nueva', 'Nueva Remesa'), ('remesa_estado', 'Cambio Estado Remesa'), ('remesa_eliminada', 'Remesa Eliminada'), ('remesa_editada', 'Remesa Editada'), ('pago_nuevo', 'Nuevo Pago'), ('pago_estado', 'Cambio Estado Pago'), ('pago_eliminado', 'Pago Eliminado'), ('pago_editado', 'Pago Editado'), ('TEST', 'Mensaje de Prueba')], max_length=20),
        ),
    ]
