# Generated by Copilot on 2026-01-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notificaciones', '0006_configuracionnotificacion_notificar_ediciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('danger', 'Error')], default='info', max_length=10)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Usuario que originó la acción (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_internas_generadas', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_internas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación Interna',
                'verbose_name_plural': 'Notificaciones Internas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificacioninterna',
            index=models.Index(fields=['recipient', 'read_at'], name='noti_int_rec_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacioninterna',
            index=models.Index(fields=['recipient', 'created_at'], name='noti_int_rec_created_idx'),
        ),
    ]
