# Generated by Django 5.2.4 on 2026-01-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0007_notificacioninterna'),
        ('remesas', '0035_moneda_alerta_fondo_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='monedas',
            field=models.ManyToManyField(blank=True, help_text='Si seleccionas monedas, este destinatario solo recibirá notificaciones cuando la operación use una de esas monedas.', related_name='destinatarios_notificacion', to='remesas.moneda'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_pago_cancelado',
            field=models.BooleanField(default=True, help_text='Recibir notificación de pago cancelado'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_pago_confirmado',
            field=models.BooleanField(default=True, help_text='Recibir notificación de pago confirmado'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_pago_editado',
            field=models.BooleanField(default=True, help_text='Recibir notificación de pago editado'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_pago_eliminado',
            field=models.BooleanField(default=True, help_text='Recibir notificación de pago eliminado'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_pago_nuevo',
            field=models.BooleanField(default=True, help_text='Recibir notificación de pago nuevo'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_remesa_cancelada',
            field=models.BooleanField(default=True, help_text='Recibir notificación de remesa cancelada'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_remesa_completada',
            field=models.BooleanField(default=True, help_text='Recibir notificación de remesa completada'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_remesa_confirmada',
            field=models.BooleanField(default=True, help_text='Recibir notificación de remesa confirmada'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_remesa_editada',
            field=models.BooleanField(default=True, help_text='Recibir notificación de remesa editada'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_remesa_eliminada',
            field=models.BooleanField(default=True, help_text='Recibir notificación de remesa eliminada'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='recibir_remesa_nueva',
            field=models.BooleanField(default=True, help_text='Recibir notificación de remesa nueva'),
        ),
        migrations.AlterField(
            model_name='lognotificacion',
            name='tipo',
            field=models.CharField(choices=[('remesa_nueva', 'Nueva Remesa'), ('remesa_estado', 'Cambio Estado Remesa'), ('remesa_confirmada', 'Remesa Confirmada'), ('remesa_completada', 'Remesa Completada'), ('remesa_cancelada', 'Remesa Cancelada'), ('remesa_eliminada', 'Remesa Eliminada'), ('remesa_editada', 'Remesa Editada'), ('pago_nuevo', 'Nuevo Pago'), ('pago_estado', 'Cambio Estado Pago'), ('pago_confirmado', 'Pago Confirmado'), ('pago_cancelado', 'Pago Cancelado'), ('pago_eliminado', 'Pago Eliminado'), ('pago_editado', 'Pago Editado'), ('TEST', 'Mensaje de Prueba')], max_length=20),
        ),
    ]
