# Generated by Django 5.2.4 on 2026-02-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0009_destinatarionotificacion_recibir_alerta_fondo_bajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lognotificacion',
            name='tipo',
            field=models.CharField(choices=[('remesa_nueva', 'Nueva Remesa'), ('remesa_estado', 'Cambio Estado Remesa'), ('remesa_confirmada', 'Remesa Confirmada'), ('remesa_completada', 'Remesa Completada'), ('remesa_cancelada', 'Remesa Cancelada'), ('remesa_eliminada', 'Remesa Eliminada'), ('remesa_editada', 'Remesa Editada'), ('pago_nuevo', 'Nuevo Pago'), ('pago_estado', 'Cambio Estado Pago'), ('pago_confirmado', 'Pago Confirmado'), ('pago_cancelado', 'Pago Cancelado'), ('pago_eliminado', 'Pago Eliminado'), ('pago_editado', 'Pago Editado'), ('alerta_fondo_bajo', 'Alerta Fondo de Caja Bajo'), ('TEST', 'Mensaje de Prueba')], max_length=20),
        ),
    ]
