# Generated by Django 5.2.4 on 2025-07-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente destinatario', max_length=255)),
                ('apellidos', models.CharField(help_text='Apellidos del cliente destinatario', max_length=255)),
                ('numero_cuenta', models.CharField(blank=True, help_text='Número de cuenta', max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254, null=True)),
                ('telefonos', models.CharField(blank=True, help_text='Teléfonos', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente receptor', max_length=255)),
                ('apellidos', models.CharField(help_text='Apellidos del cliente receptor', max_length=255)),
                ('numero_cuenta', models.CharField(blank=True, help_text='Número de cuenta', max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254, null=True)),
                ('telefonos', models.CharField(blank=True, help_text='Teléfonos', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del gestor', max_length=255)),
                ('apellidos', models.CharField(help_text='Apellidos del gestor', max_length=255)),
                ('numero_cuenta', models.CharField(blank=True, help_text='Número de cuenta', max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254, null=True)),
                ('telefonos', models.CharField(blank=True, help_text='Teléfonos', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Tipo de moneda', max_length=50)),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de moneda')),
                ('valor_actual', models.DecimalField(decimal_places=2, help_text='Valor actual de la moneda', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipodePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del destinatario', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Remesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remesa_id', models.CharField(help_text='ID único de la remesa', max_length=50, unique=True)),
                ('fecha', models.DateField(blank=True, help_text='Fecha de la remesa', null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, help_text='Importe', max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=50)),
                ('comprobante', models.ImageField(blank=True, help_text='Foto del comprobante', null=True, upload_to='comprobantes/')),
                ('cliente_destinatario', models.ForeignKey(blank=True, help_text='Cliente destinatario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='remesas.cliented')),
                ('cliente_receptor', models.ForeignKey(blank=True, help_text='Cliente receptor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='remesas.clienter')),
                ('gestor', models.ForeignKey(blank=True, help_text='Gestor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='remesas.gestor')),
                ('moneda', models.ForeignKey(blank=True, help_text='Moneda usada en la remesa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='remesas.moneda')),
                ('metodo_pago', models.ForeignKey(blank=True, help_text='Método de pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='remesas.tipodepago')),
            ],
        ),
    ]
