# Generated by Django 5.2.4 on 2025-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='moneda',
            name='valor_actual',
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(help_text='Tipo de moneda (ej: USD, EUR, COP)', max_length=50, unique=True),
        ),
    ]
