# Generated by Django 5.2.4 on 2025-07-24 12:14

import datetime
import remesas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0003_add_valor_actual_with_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remesa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='remesa',
            name='fecha',
            field=models.DateField(default=datetime.date.today, help_text='Fecha de la remesa'),
        ),
        migrations.AlterField(
            model_name='remesa',
            name='remesa_id',
            field=models.CharField(default=remesas.models.generar_id_remesa, help_text='ID único de la remesa', max_length=50, unique=True),
        ),
    ]
