# Generated by Django 5.2.4 on 2025-07-25 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0004_alter_remesa_estado_alter_remesa_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRemesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('procesada', 'Remesa Procesada'), ('cancelada', 'Remesa Cancelada'), ('satisfactoria', 'Remesa Satisfactoria'), ('error', 'Remesa con Error')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='remesas.remesa')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_remesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Remesa',
                'verbose_name_plural': 'Registros de Remesas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
