# Generated by Django 5.2.4 on 2025-07-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0005_registroremesas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remesa',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de la remesa'),
        ),
    ]
