# Generated by Django 5.2.4 on 2025-07-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0006_alter_remesa_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliented',
            name='carnet_identidad',
            field=models.CharField(blank=True, help_text='Carnet de identidad', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienter',
            name='carnet_identidad',
            field=models.CharField(blank=True, help_text='Carnet de identidad', max_length=50, null=True),
        ),
    ]
