# Generated by Django 5.2.4 on 2025-07-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0007_cliented_carnet_identidad_clienter_carnet_identidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remesa',
            name='gestor',
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
    ]
