# Generated by Django 5.2.4 on 2025-07-27 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0008_remove_remesa_gestor_delete_gestor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remesa',
            name='gestor',
            field=models.ForeignKey(blank=True, help_text='Usuario gestor que creó la remesa', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
