# Generated by Django 5.2.4 on 2025-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0009_remesa_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remesa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
    ]
