# Generated by Django 5.2.4 on 2025-07-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0010_alter_remesa_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], help_text='Tipo de pago', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad a pagar', max_digits=15)),
                ('destinatario', models.CharField(help_text='Nombre del destinatario', max_length=255)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del destinatario', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del destinatario', null=True)),
                ('carnet_identidad', models.CharField(blank=True, help_text='Carnet de identidad del destinatario', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del pago')),
                ('tipo_moneda', models.ForeignKey(blank=True, help_text='Tipo de moneda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='remesas.moneda')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
