# Generated by Django 5.2.4 on 2025-07-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0012_migrar_modelo_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='valor_actual',
            field=models.DecimalField(decimal_places=10, help_text='Valor actual de la moneda respecto al USD', max_digits=10, verbose_name='Valor Actual'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='valor_comercial',
            field=models.DecimalField(decimal_places=10, help_text='Valor comercial de la moneda para transacciones', max_digits=10, verbose_name='Valor Comercial'),
        ),
    ]
