# Generated by Django 5.2.4 on 2025-08-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0016_pago_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
