# Generated by Django 5.2.4 on 2025-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0017_alter_moneda_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante_pago',
            field=models.ImageField(blank=True, help_text='Comprobante de pago', null=True, upload_to='comprobantes_pagos/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del pago', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='pago_id',
            field=models.CharField(blank=True, help_text='ID único del pago', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tarjeta',
            field=models.CharField(blank=True, help_text='Número de tarjeta (para transferencias)', max_length=19, null=True),
        ),
    ]
