# Generated by Django 5.2.4 on 2025-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0019_auto_20250805_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='pago_id',
            field=models.CharField(blank=True, help_text='ID único del pago', max_length=50, unique=True),
        ),
    ]
