# Generated by Django 5.2.4 on 2025-08-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0020_auto_20250805_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remesa',
            name='remesa_id',
            field=models.CharField(blank=True, help_text='ID único de la remesa', max_length=50, unique=True),
        ),
    ]
