# Generated by Django 5.2.4 on 2025-08-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0022_auto_20250805_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remesa',
            name='cliente_destinatario',
        ),
        migrations.RemoveField(
            model_name='remesa',
            name='cliente_receptor',
        ),
        migrations.RemoveField(
            model_name='remesa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='remesa',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='remesa',
            name='receptor_nombre',
            field=models.CharField(default='Remitente no especificado', help_text='Nombre del remitente', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remesa',
            name='tipo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], default='transferencia', help_text='Tipo de pago', max_length=20),
        ),
    ]
