# Generated by Django 5.2.4 on 2025-08-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0023_remove_remesa_cliente_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remesa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='remesa',
            name='receptor_nombre',
            field=models.CharField(blank=True, help_text='Nombre del remitente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='remesa',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], help_text='Tipo de pago', max_length=20, null=True),
        ),
    ]
