# Generated by Django 5.2.4 on 2025-08-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0024_remesa_estado_alter_remesa_receptor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='valor_actual',
            field=models.DecimalField(decimal_places=2, help_text='Valor actual de la moneda respecto al USD', max_digits=15, verbose_name='Valor Actual'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='valor_comercial',
            field=models.DecimalField(decimal_places=2, help_text='Valor comercial de la moneda para transacciones', max_digits=15, verbose_name='Valor Comercial'),
        ),
    ]
