# Generated by Django 5.2.4 on 2025-09-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0026_alter_moneda_valor_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado del pago', max_length=20),
        ),
    ]
