# Generated by Django 5.2.4 on 2025-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0027_add_estado_to_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='tipo_moneda',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='transferencia', help_text='Tipo de moneda: efectivo o transferencia', max_length=20, verbose_name='Tipo de Moneda'),
        ),
    ]
