# Generated by Django 5.2.4 on 2025-09-06 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0028_moneda_tipo_moneda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='valor_actual',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Campo deprecado - usar ValorMoneda', max_digits=15, verbose_name='Valor Actual (Deprecado)'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='valor_comercial',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Campo deprecado - usar ValorMoneda', max_digits=15, verbose_name='Valor Comercial (Deprecado)'),
        ),
        migrations.CreateModel(
            name='TipoValorMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tipo de Valor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_valor_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Valor de Moneda',
                'verbose_name_plural': 'Tipos de Valores de Monedas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=6, default=0, help_text='Valor de la moneda respecto al USD para este tipo', max_digits=15, verbose_name='Valor')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_actualizados', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='remesas.moneda')),
                ('tipo_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_moneda', to='remesas.tipovalormoneda')),
            ],
            options={
                'verbose_name': 'Valor de Moneda',
                'verbose_name_plural': 'Valores de Monedas',
                'ordering': ['moneda__codigo', 'tipo_valor__orden'],
                'unique_together': {('moneda', 'tipo_valor')},
            },
        ),
    ]
