# Generated by Django 5.2.4 on 2025-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0029_alter_moneda_valor_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_usd_historico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto en USD calculado al momento de crear el pago (inmutable)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='valor_moneda_historico',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Valor de la moneda al momento de crear el pago (inmutable)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='remesa',
            name='monto_usd_historico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto en USD calculado al momento de crear la remesa (inmutable)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='remesa',
            name='valor_moneda_historico',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Valor de la moneda al momento de crear la remesa (inmutable)', max_digits=15, null=True),
        ),
    ]
