# Generated by Django 5.2.4 on 2025-09-18 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0030_pago_monto_usd_historico_pago_valor_moneda_historico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='editado',
            field=models.BooleanField(default=False, help_text='Indica si el pago ha sido editado después de su creación'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última edición', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario_editor',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última edición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remesa',
            name='editada',
            field=models.BooleanField(default=False, help_text='Indica si la remesa ha sido editada después de su creación'),
        ),
        migrations.AddField(
            model_name='remesa',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última edición', null=True),
        ),
        migrations.AddField(
            model_name='remesa',
            name='usuario_editor',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última edición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remesas_editadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
