# Generated by Django 5.2.4 on 2025-12-19 02:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0031_agregar_campos_edicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del pago con zona horaria de Cuba'),
        ),
        migrations.AlterField(
            model_name='remesa',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de la remesa con zona horaria de Cuba'),
        ),
    ]
