# Generated by Django 5.2.4 on 2026-01-16 21:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0032_alter_pago_fecha_creacion_alter_remesa_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRemesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_id', models.CharField(blank=True, help_text='ID único del pago', max_length=50, unique=True)),
                ('tipo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], help_text='Tipo de pago', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad a pagar', max_digits=15)),
                ('valor_moneda_historico', models.DecimalField(blank=True, decimal_places=6, help_text='Valor de la moneda al momento de crear el pago (inmutable)', max_digits=15, null=True)),
                ('monto_usd_historico', models.DecimalField(blank=True, decimal_places=2, help_text='Monto en USD calculado al momento de crear el pago (inmutable)', max_digits=15, null=True)),
                ('editado', models.BooleanField(default=False, help_text='Indica si el pago ha sido editado después de su creación')),
                ('fecha_edicion', models.DateTimeField(blank=True, help_text='Fecha y hora de la última edición', null=True)),
                ('destinatario', models.CharField(help_text='Nombre del destinatario', max_length=255)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del destinatario', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del destinatario', null=True)),
                ('carnet_identidad', models.CharField(blank=True, help_text='Carnet de identidad del destinatario', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del pago con zona horaria de Cuba')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado del pago', max_length=20)),
                ('tarjeta', models.CharField(blank=True, help_text='Número de tarjeta (para transferencias)', max_length=19, null=True)),
                ('comprobante_pago', models.ImageField(blank=True, help_text='Comprobante de pago', null=True, upload_to='comprobantes_pagos/')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del pago', null=True)),
                ('remesa', models.ForeignKey(help_text='Remesa a la que está vinculado este pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos_enlazados', to='remesas.remesa')),
                ('tipo_moneda', models.ForeignKey(blank=True, help_text='Tipo de moneda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='remesas.moneda')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó el pago', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_editor', models.ForeignKey(blank=True, help_text='Usuario que realizó la última edición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_remesa_editados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Remesa',
                'verbose_name_plural': 'Pagos de Remesas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
