# Generated by Django 5.2.4 on 2026-01-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0033_pagoremesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='fondo_caja',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fondo de caja disponible para esta moneda', max_digits=15, verbose_name='Fondo de Caja'),
        ),
    ]
