# Generated by Django 5.2.4 on 2026-01-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0034_moneda_fondo_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='alerta_fondo_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo del fondo para emitir alerta', max_digits=15, verbose_name='Alerta de Fondo Mínimo'),
        ),
    ]
