# Generated by Django 5.2.4 on 2025-07-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('contable', 'Contable')], default='gestor', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
