# Generated by Django 5.2.4 on 2025-07-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Balance'),
        ),
    ]
