# Generated by Django 5.2.4 on 2025-09-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_perfilusuario_balance'),
        ('remesas', '0029_alter_moneda_valor_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_valor_moneda',
            field=models.ForeignKey(blank=True, help_text='Tipo de valor de moneda que utiliza este usuario para los cálculos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='remesas.tipovalormoneda', verbose_name='Tipo de Valor de Moneda'),
        ),
    ]
