# Generated by Django 5.2.4 on 2026-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_perfilusuario_tipo_valor_moneda'),
        ('remesas', '0035_moneda_alerta_fondo_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='monedas_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Monedas que este usuario puede utilizar (solo para gestores y domicilios)', related_name='usuarios_asignados', to='remesas.moneda', verbose_name='Monedas Asignadas'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('contable', 'Contable'), ('domicilio', 'Domicilio')], default='gestor', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
